#!/usr/bin/env bash
# check-docs-links.sh — assert every link into the published docs site
# resolves to a real MkDocs page.
#
# Why this exists: the Lychee step in `pr.yml` passes
# `--exclude 'sergienko4.github.io/israeli-bank-scrapers/'`, because the
# site is a build artefact of this same repo — at PR time the pages a PR
# *adds* have not been deployed yet, so Lychee would fail every docs PR.
# The side effect is that NOTHING checked those links, and a README
# pointing at `/configuration/` sat there 404-ing until a human noticed.
#
# `mkdocs build --strict` only validates links *inside* docs/. It cannot
# see README.md, and it does not resolve absolute https:// URLs even when
# they point back at its own site. This script closes that gap by mapping
# each site URL back to the source file that must produce it.
#
# Usage:
#   bash .github/scripts/ci/check-docs-links.sh
#
# Exit codes:
#   0  every site link resolves to a source page
#   1  at least one link has no backing page

set -euo pipefail

SITE_PREFIX='https://sergienko4.github.io/israeli-bank-scrapers/'
REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO_ROOT" || exit 1

# `/api/` is TypeDoc output generated by the docs workflow into the site
# root. It has no .md source, so path-to-source mapping cannot verify it.
TYPEDOC_PATH='api'

FAIL=0
CHECKED=0

# Resolve a site path (e.g. "observability/redaction") to the docs/ file
# MkDocs would render it from, honouring both `foo.md` and `foo/index.md`.
resolve_source() {
  local path="$1"
  if [ -f "docs/${path}.md" ]; then
    echo "docs/${path}.md"
    return 0
  fi
  if [ -f "docs/${path}/index.md" ]; then
    echo "docs/${path}/index.md"
    return 0
  fi
  return 1
}

# `-H` keeps the filename so a failure names the file to edit. The first
# colon splits it off cleanly: the remainder still holds the `https:` of
# the URL because `%%:*` / `#*:` cut on that first colon only.
while IFS= read -r line; do
  file="${line%%:*}"
  url="${line#*:}"

  # Strip the site prefix, any anchor, and the trailing slash to get the
  # bare page path. The site root itself ("") is always valid.
  path="${url#"$SITE_PREFIX"}"
  path="${path%%#*}"
  path="${path%/}"

  # `if` rather than `[ … ] && continue`: under `errexit` a bare AND-OR
  # guard whose test fails is a footgun waiting for the next edit.
  if [ -z "$path" ] || [ "$path" = "$TYPEDOC_PATH" ]; then
    continue
  fi

  CHECKED=$((CHECKED + 1))

  if src=$(resolve_source "$path"); then
    echo "  ✓ ${path}  ←  ${src}"
  else
    FAIL=$((FAIL + 1))
    echo "  ✗ ${path}  (referenced from ${file})"
    echo "      no docs/${path}.md and no docs/${path}/index.md"
  fi
done < <(
  grep -rHoE "${SITE_PREFIX}[A-Za-z0-9._/#-]*" \
    --include='*.md' README.md docs/ 2>/dev/null | sort -u
)

echo ""
if [ "$FAIL" -gt 0 ]; then
  echo "check-docs-links: ${FAIL} of ${CHECKED} site links have no backing page."
  echo "Either add the page under docs/ (and to mkdocs.yml nav), or fix the link."
  exit 1
fi

echo "check-docs-links: all ${CHECKED} site links resolve to a docs/ page."
exit 0
