/**
 * Per-bank Mode B mirror manifest — declarative state machine that
 * walks a production scraper through every PHASE_CHAIN phase.
 *
 * Generated by the harvester (one-time real-bank capture) and committed
 * to the repo at `src/Tests/Integration/fixtures/banks/<bank>/manifest.json`.
 *
 * The simulator ({@link ./MirrorSimulator.ts}) reads this manifest, watches
 * Playwright `route` events, and:
 *
 *   1. matches each incoming request against the {@link IMirrorTransition}
 *      predicates allowed in the simulator's CURRENT phase,
 *   2. fulfils with the matched response fixture (status + headers + body),
 *   3. advances state to `advanceTo` ONLY when a transition predicate
 *      carries one — multiple unordered same-phase responses are allowed,
 *   4. counts every unmatched request via {@link MirrorEscapeClassifier} so
 *      tests can fail on fatal app/API/document escapes without choking on
 *      benign analytics/favicons.
 *
 * Design rationale (per Phase 11 rubber-duck cycle 2 finding #1):
 * URL+method matching alone is too weak. Manifest entries also constrain
 * resource type, optional POST body shape, and optional cookie/header
 * predicates so OTP submission with a wrong nonce is rejected, and silent
 * "first match advances" bugs are impossible.
 *
 * @see ./MirrorSimulator.ts
 * @see ../Phases/IntegrationPhase.ts
 */

import type { IntegrationPhase } from '../Phases/IntegrationPhase.js';

/** Playwright resource type subset relevant to the simulator. */
type MirrorResourceType =
  | 'document'
  | 'fetch'
  | 'xhr'
  | 'script'
  | 'stylesheet'
  | 'image'
  | 'font'
  | 'media'
  | 'websocket'
  | 'other';

/** HTTP method subset the simulator routes on. */
type MirrorMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD';

/**
 * Predicate over an incoming request's POST body. The simulator deserializes
 * the body as JSON (if `shape: 'json'`) or as URL-encoded form (if
 * `shape: 'form'`) and asserts that every `expectations` entry
 * matches the actual value.
 *
 * Used to enforce that OTP-FILL POSTs include the deterministic test code
 * AND the challenge nonce the OTP-TRIGGER fixture issued.
 */
interface IPostDataPredicate {
  readonly shape: 'json' | 'form';
  readonly expectations: Readonly<Record<string, string>>;
}

/**
 * Header predicate — a header MUST be present and (when `value` is
 * provided) match exactly. Used to assert session cookies issued by an
 * earlier fixture flow through later requests.
 */
interface IHeaderPredicate {
  readonly name: string;
  readonly value?: string;
}

/** Cookie predicate, semantically identical to {@link IHeaderPredicate}. */
interface ICookiePredicate {
  readonly name: string;
  readonly value?: string;
}

/**
 * Response payload the simulator fulfils a matched request with. The body
 * is loaded from the file relative to the bank's fixture root.
 */
interface IMirrorResponse {
  readonly status: number;
  readonly contentType: string;
  /** Fixture file path relative to the bank fixture root. */
  readonly bodyFile: string;
  /** Extra response headers (e.g. `Set-Cookie` for challenge nonce). */
  readonly headers?: Readonly<Record<string, string>>;
}

/**
 * One transition rule. The simulator iterates the bank's transitions and
 * applies the first whose predicates ALL match the request AND whose
 * `phase` is the simulator's current phase.
 *
 * If `advanceTo` is undefined the rule serves a side-channel
 * resource (e.g. a JSON balance endpoint inside DASHBOARD) without
 * changing the simulator's state.
 *
 * If multiple rules match the same request the simulator throws — the
 * manifest must be deterministic by construction.
 */
interface IMirrorTransition {
  readonly phase: IntegrationPhase;
  readonly method: MirrorMethod;
  readonly urlPattern: string;
  readonly resourceType?: MirrorResourceType;
  readonly postData?: IPostDataPredicate;
  readonly headers?: readonly IHeaderPredicate[];
  readonly cookies?: readonly ICookiePredicate[];
  readonly response: IMirrorResponse;
  readonly advanceTo?: IntegrationPhase;
}

/** Full per-bank manifest committed at `manifest.json`. */
interface IMirrorManifest {
  readonly bankId: string;
  readonly originUrl: string;
  /** Starting phase — almost always `INIT`. */
  readonly startPhase: IntegrationPhase;
  /** Terminal phase — simulator stops advancing on entry. */
  readonly endPhase: IntegrationPhase;
  readonly transitions: readonly IMirrorTransition[];
}

export type {
  ICookiePredicate,
  IHeaderPredicate,
  IMirrorManifest,
  IMirrorResponse,
  IMirrorTransition,
  IPostDataPredicate,
  MirrorMethod,
  MirrorResourceType,
};
